feat: option to exclude specific methods
raeperd/recvcheck pull request #11
Opened 2024-11-27 21:40 UTC by ldez

This is a draft of a proposal.

I used a glob-based expression, but it can be a regular expression or something else.

Related to https://github.com/raeperd/recvcheck/pull/8#issuecomment-2480381982
Fixes #9

2024-11-27 21:45 UTC, ccoVeille commented on analyzer.go
> +}
Is it normal ypu always return false?

It looks like a strange signature

2024-12-01 06:53 UTC, raeperd commented
To me, `*.MarshalYAML` or `MarshalYAML` does the same. 
So maybe we can safely remove glob pattern, and simplifies config with exact match only. (ex `type.MarshalYAML`)

2024-12-26 13:57 UTC, raeperd commented
@ldez 
is there any thing more to be done in this pr? maybe I can help

2024-12-26 14:08 UTC, ldez commented
I was just waiting for your feeback

2024-12-26 14:10 UTC, raeperd commented
@ldez 
Sorry.. I read your comment right after your comment,  and add emoji to show you I agreed with your comment. I will start review now.

2024-12-26 14:29 UTC, raeperd requested changes

2024-12-26 14:55 UTC, raeperd approved these changes
lgtm

2024-12-26 16:24 UTC, merged